name: bf528_project_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - seaborn
  - matplotlib
  - scanpy
  - scrublet
  - pip
  - pip:
    - celltypist
